[phases.setup]
nixPkgs = ["python311", "uv", "gcc"]

[variables]
UV_PYTHON_DOWNLOADS = "never"

[phases.install]
cmds = [
    "uv venv /opt/venv",
    "uv pip install -r requirements.txt --python /opt/venv"
]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:80 app:app"
